# Generated by Django 5.1.7 on 2025-07-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kullanici", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("yonetici", "Yönetici"),
                    ("personel", "Personel"),
                    ("depo_gorevlisi", "Depo Görevlisi"),
                ],
                default="personel",
                max_length=20,
            ),
        ),
    ]
